version: 2.1

jobs:
  build-gcc:
    docker:
      - image: charlesnicholson/circleci-images:latest
    steps:
      - checkout
      - run:
          command: ./b --cfg Debug -v
      - persist_to_workspace:
          root: workspace
          paths:
            - out

  add_1_2:
    docker:
      - image: charlesnicholson/circleci-images:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
        command: ls -al /tmp/workspace/out #|
          #/tmp/workspace/out/add 1.txt 2.txt /tmp/workspace/3.txt
          #cat /tmp/workspace/3.txt

workflows:
  submit-gate:
    jobs:
      - build-gcc
      - add_1_2:
        requires:
          - build-gcc
