version: 2.1

jobs:
  build-gcc:
    docker:
      - image: charlesnicholson/circleci-images:latest
    steps:
      - checkout
      - run:
          command: ./b
      - persist_to_workspace:
          root: /root/project
          paths:
            - out/*

  add_1_2:
    docker:
      - image: charlesnicholson/circleci-images:latest
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          command: |
            out/add 1.txt 2.txt 3.txt
            cat 3.txt
      - persist_to_workspace:
          root: /root/project
          paths:
            - 3.txt

workflows:
  version: 2
  submit-gate:
    jobs:
      - build-gcc
      - add_1_2:
          requires:
            - build-gcc
