version: 2.1

jobs:
  build:
    docker:
      - image: charlesnicholson/circleci-images:latest
    steps:
      - checkout
      - run:
          command: ./b --cfg Debug -v
      - persist_to_workspace:
          root: workspace
          paths:
            - out

  add_1_2:
    docker:
      - image: charlesnicholson/circleci-images:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
        command: |
          /tmp/workspace/out/add 1.txt 2.txt /tmp/workspace/3.txt
          cat /tmp/workspace/3.txt


  build-clang-release:
    docker:
      - image: charlesnicholson/circleci-images:latest
    environment:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
    steps:
      - checkout
      - run:
          command: ./b --cfg Release -v

workflows:
  submit-gate:
    jobs:
      - build
      - add_1_2:
        requires:
          - build
